name: Build Data and Deploy to Netlify

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Dependencies for Scraper
        working-directory: ./scraper
        run: npm install

      - name: Install Dependencies for datastore
        working-directory: ./datastore
        run: npm install

      - name: Install Dependencies for datastore
        working-directory: ./netlify/functions/server
        run: npm install

      - name: Build Data
        env:
            NETLIFY_URL: ${{ secrets.NETLIFY_URL }}
        run: npm run build-data

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
